//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XAUMobile.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XAUMobile.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achieved.
        /// </summary>
        internal static string AchievementAchieved {
            get {
                return ResourceManager.GetString("AchievementAchieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Unlock.
        /// </summary>
        internal static string AchievementConfirmUnlock {
            get {
                return ResourceManager.GetString("AchievementConfirmUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to unlock.
        /// </summary>
        internal static string AchievementConfirmUnlockMessage {
            get {
                return ResourceManager.GetString("AchievementConfirmUnlockMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Achievements.
        /// </summary>
        internal static string AchievementFilter {
            get {
                return ResourceManager.GetString("AchievementFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string AchievementFilterAll {
            get {
                return ResourceManager.GetString("AchievementFilterAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked.
        /// </summary>
        internal static string AchievementFilterLocked {
            get {
                return ResourceManager.GetString("AchievementFilterLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlocked.
        /// </summary>
        internal static string AchievementFilterUnlocked {
            get {
                return ResourceManager.GetString("AchievementFilterUnlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        internal static string AchievementInProgress {
            get {
                return ResourceManager.GetString("AchievementInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Started.
        /// </summary>
        internal static string AchievementNotStarted {
            get {
                return ResourceManager.GetString("AchievementNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievement Unlocked.
        /// </summary>
        internal static string AchievementUnlocked {
            get {
                return ResourceManager.GetString("AchievementUnlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was successfully unlocked.
        /// </summary>
        internal static string AchievementUnlockedMessage {
            get {
                return ResourceManager.GetString("AchievementUnlockedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already Unlocked.
        /// </summary>
        internal static string AlreadyUnlocked {
            get {
                return ResourceManager.GetString("AlreadyUnlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has already been unlocked and cannot be unlocked again.
        /// </summary>
        internal static string AlreadyUnlockedMessage {
            get {
                return ResourceManager.GetString("AlreadyUnlockedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And.
        /// </summary>
        internal static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Announcements.
        /// </summary>
        internal static string Announcements {
            get {
                return ResourceManager.GetString("Announcements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Settings.
        /// </summary>
        internal static string AppSettings {
            get {
                return ResourceManager.GetString("AppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beta.
        /// </summary>
        internal static string Beta {
            get {
                return ResourceManager.GetString("Beta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a beta feature. It may be an incomplete feature or you may encounter errors..
        /// </summary>
        internal static string BetaFeature {
            get {
                return ResourceManager.GetString("BetaFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page is still in beta. If you experience any issues, please report it in the Discord.
        /// </summary>
        internal static string BetaWarning {
            get {
                return ResourceManager.GetString("BetaWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Theme Color.
        /// </summary>
        internal static string ChangeThemeColor {
            get {
                return ResourceManager.GetString("ChangeThemeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Update.
        /// </summary>
        internal static string CheckForUpdate {
            get {
                return ResourceManager.GetString("CheckForUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied.
        /// </summary>
        internal static string Copied {
            get {
                return ResourceManager.GetString("Copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied to Clipboard.
        /// </summary>
        internal static string CopiedToClipboard {
            get {
                return ResourceManager.GetString("CopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has been copied to your clipboard.
        /// </summary>
        internal static string CopiedToClipboardMessage {
            get {
                return ResourceManager.GetString("CopiedToClipboardMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        internal static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        internal static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        internal static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait until you get the install prompt.
        /// </summary>
        internal static string DownloadingPrompt {
            get {
                return ResourceManager.GetString("DownloadingPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Update... Please Wait..
        /// </summary>
        internal static string DownloadingUpdate {
            get {
                return ResourceManager.GetString("DownloadingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Signature.
        /// </summary>
        internal static string EnableSignature {
            get {
                return ResourceManager.GetString("EnableSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter App.
        /// </summary>
        internal static string EnterApp {
            get {
                return ResourceManager.GetString("EnterApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter custom signature here.
        /// </summary>
        internal static string EnterCustomSignature {
            get {
                return ResourceManager.GetString("EnterCustomSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Game Name.
        /// </summary>
        internal static string EnterGameName {
            get {
                return ResourceManager.GetString("EnterGameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter New Value.
        /// </summary>
        internal static string EnterNewValue {
            get {
                return ResourceManager.GetString("EnterNewValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Product ID / Xbox or Microsoft Store link.
        /// </summary>
        internal static string EnterProductIdorLink {
            get {
                return ResourceManager.GetString("EnterProductIdorLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Title ID.
        /// </summary>
        internal static string EnterTitleID {
            get {
                return ResourceManager.GetString("EnterTitleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid Gamertag.
        /// </summary>
        internal static string EnterValidGamertag {
            get {
                return ResourceManager.GetString("EnterValidGamertag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid Title ID.
        /// </summary>
        internal static string EnterValidTitleId {
            get {
                return ResourceManager.GetString("EnterValidTitleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Xbox Token Here.
        /// </summary>
        internal static string EnterXauthHere {
            get {
                return ResourceManager.GetString("EnterXauthHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Token Manually.
        /// </summary>
        internal static string EnterXauthManually {
            get {
                return ResourceManager.GetString("EnterXauthManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to fetch Title ID.
        /// </summary>
        internal static string FailedFetchTitleId {
            get {
                return ResourceManager.GetString("FailedFetchTitleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to fetch gamertag information.
        /// </summary>
        internal static string FailedGamertagInfo {
            get {
                return ResourceManager.GetString("FailedGamertagInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to export games.
        /// </summary>
        internal static string FailedToExportGames {
            get {
                return ResourceManager.GetString("FailedToExportGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load stats. The TitleID may be wrong or the game has no stats.
        /// </summary>
        internal static string FailedToLoadStats {
            get {
                return ResourceManager.GetString("FailedToLoadStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to spoof game.
        /// </summary>
        internal static string FailedToSpoofGame {
            get {
                return ResourceManager.GetString("FailedToSpoofGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must use PC Xbox Token to spoof.
        /// </summary>
        internal static string FailedToSpoofGameMessage {
            get {
                return ResourceManager.GetString("FailedToSpoofGameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to fetch Title ID.
        /// </summary>
        internal static string FailFetchTitleId {
            get {
                return ResourceManager.GetString("FailFetchTitleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        internal static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Games.
        /// </summary>
        internal static string FilterAllGamesOption {
            get {
                return ResourceManager.GetString("FilterAllGamesOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Games.
        /// </summary>
        internal static string FilterGames {
            get {
                return ResourceManager.GetString("FilterGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete Games.
        /// </summary>
        internal static string FilterIncompleteGamesOption {
            get {
                return ResourceManager.GetString("FilterIncompleteGamesOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follower Count.
        /// </summary>
        internal static string FollowerCount {
            get {
                return ResourceManager.GetString("FollowerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following Count.
        /// </summary>
        internal static string FollowingCount {
            get {
                return ResourceManager.GetString("FollowingCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamerscore.
        /// </summary>
        internal static string Gamerscore {
            get {
                return ResourceManager.GetString("Gamerscore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamertag.
        /// </summary>
        internal static string Gamertag {
            get {
                return ResourceManager.GetString("Gamertag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games Exported Successfully.
        /// </summary>
        internal static string GamesExportedSuccessfully {
            get {
                return ResourceManager.GetString("GamesExportedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO GAMES FOUND..
        /// </summary>
        internal static string GamesSearchNoGamesFound {
            get {
                return ResourceManager.GetString("GamesSearchNoGamesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEARCH BY GAME NAME.
        /// </summary>
        internal static string GamesSearchPlaceholder {
            get {
                return ResourceManager.GetString("GamesSearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Title ID.
        /// </summary>
        internal static string GetTitleId {
            get {
                return ResourceManager.GetString("GetTitleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Later.
        /// </summary>
        internal static string Later {
            get {
                return ResourceManager.GetString("Later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Achievements.
        /// </summary>
        internal static string LoadAchievements {
            get {
                return ResourceManager.GetString("LoadAchievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option does not spoof or add the game to your Xbox game list. It will only load the achievements for the game.
        /// </summary>
        internal static string LoadManualAchievementsWarning {
            get {
                return ResourceManager.GetString("LoadManualAchievementsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Stats.
        /// </summary>
        internal static string LoadStats {
            get {
                return ResourceManager.GetString("LoadStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failed.
        /// </summary>
        internal static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve your Auth Token. Press the button only after you have reached your profile page..
        /// </summary>
        internal static string LoginPageFailMessage {
            get {
                return ResourceManager.GetString("LoginPageFailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem? Click To Get Xbox Token.
        /// </summary>
        internal static string LoginPageProblemButton {
            get {
                return ResourceManager.GetString("LoginPageProblemButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xbox Token saved successfully. Remember that spoofing does not work for this token. You will now be redirected to the Home page.
        /// </summary>
        internal static string LoginPageSuccessMessage {
            get {
                return ResourceManager.GetString("LoginPageSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Successful.
        /// </summary>
        internal static string LoginSuccessful {
            get {
                return ResourceManager.GetString("LoginSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with Xbox.
        /// </summary>
        internal static string LoginWithXbox {
            get {
                return ResourceManager.GetString("LoginWithXbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s get you logged in... After you reach the profile page, it should automatically get your Xbox Token.\n\nIf it does not, press on the [Problem? Click to Get Xbox Token] button on the bottom of your Xbox profile page..
        /// </summary>
        internal static string MainPagePromptForLoginPage {
            get {
                return ResourceManager.GetString("MainPagePromptForLoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THIS APP IS STILL IN BETA. PLEASE REPORT ANY ISSUES IN THE DISCORD. Put your Xbox Token before navigating to other pages. The App will not function without your Xbox Token..
        /// </summary>
        internal static string MainPageWarning {
            get {
                return ResourceManager.GetString("MainPageWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night Mode.
        /// </summary>
        internal static string NightMode {
            get {
                return ResourceManager.GetString("NightMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Achievements.
        /// </summary>
        internal static string NoAchievements {
            get {
                return ResourceManager.GetString("NoAchievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO ACHIEVEMENTS FOUND.
        /// </summary>
        internal static string NoAchievementsFound {
            get {
                return ResourceManager.GetString("NoAchievementsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This game has no achievements.
        /// </summary>
        internal static string NoAchievementsMessage {
            get {
                return ResourceManager.GetString("NoAchievementsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No games to export..
        /// </summary>
        internal static string NoGamesToExport {
            get {
                return ResourceManager.GetString("NoGamesToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No stat selected or no value entered.
        /// </summary>
        internal static string NoStatsSelected {
            get {
                return ResourceManager.GetString("NoStatsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some parts of this page may still be in English only..
        /// </summary>
        internal static string NotLocalized {
            get {
                return ResourceManager.GetString("NotLocalized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        internal static string OR {
            get {
                return ResourceManager.GetString("OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Mode.
        /// </summary>
        internal static string PrivacyMode {
            get {
                return ResourceManager.GetString("PrivacyMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product ID Examples.
        /// </summary>
        internal static string ProductIdExamples {
            get {
                return ResourceManager.GetString("ProductIdExamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached the rate limit. Try again later.
        /// </summary>
        internal static string RateLimitMessage {
            get {
                return ResourceManager.GetString("RateLimitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Settings.
        /// </summary>
        internal static string ResetSettings {
            get {
                return ResourceManager.GetString("ResetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Signature to Default.
        /// </summary>
        internal static string ResetSignatureDefault {
            get {
                return ResourceManager.GetString("ResetSignatureDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by Game Name.
        /// </summary>
        internal static string SearchByGameName {
            get {
                return ResourceManager.GetString("SearchByGameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on Game to Copy Title ID to Clipboard.
        /// </summary>
        internal static string SearchCopyToClipboard {
            get {
                return ResourceManager.GetString("SearchCopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid game name.
        /// </summary>
        internal static string SearchEnterValidGameName {
            get {
                return ResourceManager.GetString("SearchEnterValidGameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Games Found.
        /// </summary>
        internal static string SearchNoGamesFound {
            get {
                return ResourceManager.GetString("SearchNoGamesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No games were found matching your search. Please check your spelling. If the game is not in our database, you can use the Product ID search to automatically add the game.
        /// </summary>
        internal static string SearchNoGamesFoundMessage {
            get {
                return ResourceManager.GetString("SearchNoGamesFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert Product ID to Xbox Title ID.
        /// </summary>
        internal static string SearchProductConvertMessage {
            get {
                return ResourceManager.GetString("SearchProductConvertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid link or product ID.
        /// </summary>
        internal static string SearchProductEnterValidProductId {
            get {
                return ResourceManager.GetString("SearchProductEnterValidProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve Xbox Title ID.
        /// </summary>
        internal static string SearchProductError {
            get {
                return ResourceManager.GetString("SearchProductError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        internal static string SearchTabGame {
            get {
                return ResourceManager.GetString("SearchTabGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamertag.
        /// </summary>
        internal static string SearchTabGamertag {
            get {
                return ResourceManager.GetString("SearchTabGamertag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product ID.
        /// </summary>
        internal static string SearchTabProductId {
            get {
                return ResourceManager.GetString("SearchTabProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        internal static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Color.
        /// </summary>
        internal static string SelectedColor {
            get {
                return ResourceManager.GetString("SelectedColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Stat.
        /// </summary>
        internal static string SelectedStat {
            get {
                return ResourceManager.GetString("SelectedStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        internal static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature Settings.
        /// </summary>
        internal static string SignatureSettings {
            get {
                return ResourceManager.GetString("SignatureSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Optional) Select a User-Agent.
        /// </summary>
        internal static string SpoofingUserAgent {
            get {
                return ResourceManager.GetString("SpoofingUserAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Spoofing does not work with Xbox Login. You will need to grab the token from PC using XAU and manually add it.
        /// </summary>
        internal static string SpoofingWarning {
            get {
                return ResourceManager.GetString("SpoofingWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Spoofing.
        /// </summary>
        internal static string StartSpoofing {
            get {
                return ResourceManager.GetString("StartSpoofing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Stats request was sent to Xbox..
        /// </summary>
        internal static string StatsUpdateRequestSent {
            get {
                return ResourceManager.GetString("StatsUpdateRequestSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Spoofing.
        /// </summary>
        internal static string StopSpoofing {
            get {
                return ResourceManager.GetString("StopSpoofing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        internal static string TabBarGames {
            get {
                return ResourceManager.GetString("TabBarGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string TabBarHome {
            get {
                return ResourceManager.GetString("TabBarHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc.
        /// </summary>
        internal static string TabBarMisc {
            get {
                return ResourceManager.GetString("TabBarMisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string TabBarSearch {
            get {
                return ResourceManager.GetString("TabBarSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string TabBarUser {
            get {
                return ResourceManager.GetString("TabBarUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spoof Game.
        /// </summary>
        internal static string TabTitleSpoofGame {
            get {
                return ResourceManager.GetString("TabTitleSpoofGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stats Editor.
        /// </summary>
        internal static string TabTitleStatsEditor {
            get {
                return ResourceManager.GetString("TabTitleStatsEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme &amp; Language Settings.
        /// </summary>
        internal static string ThemeLanguageSettings {
            get {
                return ResourceManager.GetString("ThemeLanguageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Played.
        /// </summary>
        internal static string TimePlayed {
            get {
                return ResourceManager.GetString("TimePlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title ID.
        /// </summary>
        internal static string Title_ID {
            get {
                return ResourceManager.GetString("Title ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title-Based Games Only.
        /// </summary>
        internal static string TitleBasedGamesOnly {
            get {
                return ResourceManager.GetString("TitleBasedGamesOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title ID.
        /// </summary>
        internal static string TitleID {
            get {
                return ResourceManager.GetString("TitleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Title ID {0} for {1} was copied to the clipboard..
        /// </summary>
        internal static string TitleIdClipboard {
            get {
                return ResourceManager.GetString("TitleIdClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About XAUMobile.
        /// </summary>
        internal static string ToolBarMenuAboutXAU {
            get {
                return ResourceManager.GetString("ToolBarMenuAboutXAU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord Server.
        /// </summary>
        internal static string ToolBarMenuDiscord {
            get {
                return ResourceManager.GetString("ToolBarMenuDiscord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string ToolBarMenuSettings {
            get {
                return ResourceManager.GetString("ToolBarMenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Games.
        /// </summary>
        internal static string TotalGames {
            get {
                return ResourceManager.GetString("TotalGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock Date.
        /// </summary>
        internal static string UnlockDate {
            get {
                return ResourceManager.GetString("UnlockDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported.
        /// </summary>
        internal static string UnsupportedAchievement {
            get {
                return ResourceManager.GetString("UnsupportedAchievement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is a event-based achievement and cannot be unlocked.
        /// </summary>
        internal static string UnsupportedAchievementMessage {
            get {
                return ResourceManager.GetString("UnsupportedAchievementMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported Title.
        /// </summary>
        internal static string UnsupportedTitle {
            get {
                return ResourceManager.GetString("UnsupportedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contains event-based achievements which are not supported.
        /// </summary>
        internal static string UnsupportedTitleMessage {
            get {
                return ResourceManager.GetString("UnsupportedTitleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Available.
        /// </summary>
        internal static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Check.
        /// </summary>
        internal static string UpdateCheck {
            get {
                return ResourceManager.GetString("UpdateCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is already up to date.
        /// </summary>
        internal static string UpdateCheckAlreadyUpToDate {
            get {
                return ResourceManager.GetString("UpdateCheckAlreadyUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Game Stats.
        /// </summary>
        internal static string UpdateGameStats {
            get {
                return ResourceManager.GetString("UpdateGameStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version ({0}) is available!\n\nChangelog:\n{1}\n\nWould you like to update now?.
        /// </summary>
        internal static string UpdateMessage {
            get {
                return ResourceManager.GetString("UpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Stats.
        /// </summary>
        internal static string UpdateStats {
            get {
                return ResourceManager.GetString("UpdateStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade Required.
        /// </summary>
        internal static string UpgradeRequired {
            get {
                return ResourceManager.GetString("UpgradeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A newer version of XAUMobile is required to use the search function. Please update to continue.
        /// </summary>
        internal static string UpgradeRequiredMessage {
            get {
                return ResourceManager.GetString("UpgradeRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check and update your Xbox Authorization Token.
        /// </summary>
        internal static string UserPageLoginMessageFail {
            get {
                return ResourceManager.GetString("UserPageLoginMessageFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can now use the app. Enjoy!.
        /// </summary>
        internal static string UserPageLoginMessageSuccess {
            get {
                return ResourceManager.GetString("UserPageLoginMessageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presence State.
        /// </summary>
        internal static string UserPagePresenceState {
            get {
                return ResourceManager.GetString("UserPagePresenceState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presence Text.
        /// </summary>
        internal static string UserPagePresenceText {
            get {
                return ResourceManager.GetString("UserPagePresenceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xbox Reputation.
        /// </summary>
        internal static string UserPageXboxRep {
            get {
                return ResourceManager.GetString("UserPageXboxRep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree to the Terms and Conditions.
        /// </summary>
        internal static string WelcomePageAgreeToc {
            get {
                return ResourceManager.GetString("WelcomePageAgreeToc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By using this app, you agree to the following terms:.
        /// </summary>
        internal static string WelcomePageFollowingTerms {
            get {
                return ResourceManager.GetString("WelcomePageFollowingTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. This app is free and you did not pay someone for it..
        /// </summary>
        internal static string WelcomePageTerms1 {
            get {
                return ResourceManager.GetString("WelcomePageTerms1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. You will not join the Discord and ask stupid questions..
        /// </summary>
        internal static string WelcomePageTerms2 {
            get {
                return ResourceManager.GetString("WelcomePageTerms2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Do NOT share your Xbox token with anyone! Treat it like a password for your account..
        /// </summary>
        internal static string WelcomePageTerms3 {
            get {
                return ResourceManager.GetString("WelcomePageTerms3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. You understand the risks that come with using the XAU Mobile application..
        /// </summary>
        internal static string WelcomePageTerms4 {
            get {
                return ResourceManager.GetString("WelcomePageTerms4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. Unlocking achievements or spoofing games using this app may violate Xbox/Microsoft terms of service. We are not responsible for any penalties or bans that may occur as a result..
        /// </summary>
        internal static string WelcomePageTerms5 {
            get {
                return ResourceManager.GetString("WelcomePageTerms5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6. You agree that the developer of this app has warned your stupid ass and they are not responsible for anything..
        /// </summary>
        internal static string WelcomePageTerms6 {
            get {
                return ResourceManager.GetString("WelcomePageTerms6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not put your Xbox Authentication Token. You can use the Xbox Login button or manually paste your Token if you have it..
        /// </summary>
        internal static string XauthNotSet {
            get {
                return ResourceManager.GetString("XauthNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xbox Login.
        /// </summary>
        internal static string XboxLogin {
            get {
                return ResourceManager.GetString("XboxLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xbox Token.
        /// </summary>
        internal static string XboxToken {
            get {
                return ResourceManager.GetString("XboxToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
